baseURL = "https://yoichi-beer.netlify.app/"
languageCode = "ja"
hasCJKLanguage = true
title = "loose talk"
theme = "bodhi"
googleAnalytics = "UA-175438985-1"

[params]
    # subtitle = "ゆるい話"
    avatar = "/images/lily.png"
    author = "yoichibeer"
    commentoSrc = "https://commento.example.com/js/commento.js"
    disableSearch = false

[[menu.main_right]]
name = "tags"
url = "/tags"
weight = 1

[[menu.main_right]]
name = "about"
url = "/about/"
weight = 2

[markup.goldmark.renderer]
unsafe= true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    noClasses = true
    style = "emacs"
    tabWidth = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/yoichibeer"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/yoichibeer"
